### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by HaizeaR** [Jondiii/appContenedores#3]
**Errores:**
- [ ] Plan día 1 no sale mapa (Haizea) 
- [ ] Si se planifica varias veces seguidas sin cerrar la app, se van añadiendo nan en el listado de contenedores de sample.txt. Se ha guardado un ejemplo de esto en sampleErroneo.txt.    

- [ ] Revisar como se añaden nuevos camiones
> _(Jon: está "arreglado", aunque lo que hace ahora es volver a leer el .csv antes de empezar a planificar)._

**TODOs:**
Urgentes:
- [ ] Mirar que el depot usado en los cálculos coincida con el depot del mapa.
- [ ] Que el plan inicial se genere teniendo en cuenta los datos introducidos, no los aleatorios.
- [ ] **sacarPlan** no está usando los datos del csv, tenemos que cambiar el método.

Menos importantes:
- [ ] Que Resultados se actualice cada vez que le demos a planificar.
- [ ] Que Plan se actualice cada vez que le demos a planificar.
- [x] Buscar forma para no tener que hardcodear el número de días para saber cuántos ficheros mapas leer (línea 1493 aprox, tiene puesto un #TODO).
- [ ] Que no se pueda darle a planificar sin haber especificado número de días y la capacidad de los contenedores.

**Ideas:**
- [ ] Tener ficheros con listados de contenedores listos para leer directamente por cada municipio.
- [ ] ¿Qué se puedan subir ficheros desde la app?

**Solucionado:**
- [X] Eliminar las tildes que se guardan en el txt.
- [X] Cuando se planifica habiendo modificado algún valor de los camiones existentes y sin haber añadido número de días ni capacidad contenedores sale invalid literal for int() with base 10: '' en la línea 456 / 1550.
> _(**Solucionado**: el problema era que estaba en formato String y no en int)_
- [X] Cuando se planifica sin haber modificado nada y sin añadir número de días ni capacidad contenedores sale division by zero en la línea 124.     
- [X] Cuando se le da a Guardar en Contenedores sin hacer cambios sale Index out of range en la línea 1374. 
> _(Comentario Haizea: no me ha pasado pero lo tengo en cuenta )_
- [X] Crear botón para poder eliminar camiones de la tabla 
- [X] Añadir tabs por cada día planificado.
- [x] Si hacemos doble click en la fila  para añadir Camiones pero no llegamos a añadir nada sale el error invalid literal for int() with base 10: ''
> _(Esto ocurre porque si o si se tiene que incluir el núm de dias)_
- [x] Cada vez que se cierra la app sale "Release of profile requested but WebEnginePage still not deleted. Expect troubles !"
 >_(Jon: ya no me sale)_
>_(Haizea: creo que a mi tampoco)_
- [x] Asegurarnos de las unidades de los datos son coherentes en todo el programa. Definir las unidades en las que están las capacidades de los contenedores, las de los camiones, las distancias, etc.
